project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"
    - "resource/"
    - "assignment/"
    - "lesson/"
    - "example/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/ecology.csl

website:
  title: "Intro to Spatial Data in R"
  site-url: "https://isdrfall24.classes.spaseslab.com"
  description: "Use R to load, visualize, and analyze spatial data"

  favicon: "/files/iSDR_logo.png"

  # twitter-card:
  #   image: "/files/social-image-f22.png"
  #   card-style: summary_large_image
  #   creator: "@MwilliamsonMatt"
    # site: "@MwilliamsonMatt"

  # open-graph:
  #   image: "/files/social-image-f22.png"
  #   locale: en_US

  navbar:
    pinned: true
    background: "#027373"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Lessons"
        file: lesson/index.qmd
      - text: "Resources"
        file: resource/index.qmd
      - icon: slack
        href: "https://ecostatsbsu.slack.com/archives/C07DGC07AMB"
        aria-label: Slack
      - icon: github
        href: "https://github.com/BSU-Spatial-Data-in-R-Fall2024"
        aria-label: GitHub
      - icon: cloud-fill
        href: "https://rstudio-lxp-01.boisestate.edu"
        aria-label: Rstudio

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: "#7C4A89"
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "1: Introduction to the Course"
              file: content/01-content.qmd
            - text: "2: Why Geographic Analysis"
              file: content/02-content.qmd
            - text: "3: Introduction to Spatial Data"
              file: content/03-content.qmd
            - text: "4: Intro to Spatial Data with R"
              file: content/04-content.qmd
            - text: "5: Literate Programming, Quarto, Workflows"
              file: content/05-content.qmd
            - text: "6: Areal Data - Coordinates and Geometries"
              file: content/06-content.qmd
            - text: "7: Areal Data - Vector Data"
              file: content/07-content.qmd
            - text: "8: Areal Data - Raster Data"
              file: content/08-content.qmd
            - text: "9: Intro to Mapping Geographic Data"
              file: content/09-content.qmd
            - text: "10: Operations with Vector Data I"
              file: content/10-content.qmd
            - text: "11: Operations with Vector Data II"
              file: content/11-content.qmd
            - text: "12: Operations with Raster Data I"
              file: content/12-content.qmd
            - text: "13: Operations with Raster Data II"
              file: content/13-content.qmd
            # - text: "15: Combining Tabular and Spatial Data"
            #   file: content/15-content.qmd
            # - text: "16: Combining Vectors and Continuous Rasters"
            #   file: content/16-content.qmd
            # - text: "17: Combining Vectors and Categorical Rasters"
            #   file: content/17-content.qmd
            # - text: "18: Point Patterns"
            #   file: content/18-content.qmd
            # - text: "19: Interpolation"
            #   file: content/19-content.qmd
            # - text: "20: Proximity and Areal Data"
            #   file: content/20-content.qmd
            # - text: "21: Spatial Autocorrelation"
            #   file: content/21-content.qmd
            # - text: "22: Statistical Modelling I"
            #   file: content/22-content.qmd
            # - text: "23: Statistical Modelling II"
            #   file: content/23-content.qmd
            # - text: "24: Statistical Modelling III"
            #   file: content/24-content.qmd
            # - text: "25: Movement and Networks I"
            #   file: content/25-content.qmd
            # - text: "26: Movement and Networks II"
            #   file: content/26-content.qmd
            # - text: "29: Data Visualization and Maps I"
            #   file: content/29-content.qmd
            # - text: "30: Data Visualization and Maps II"
            #   file: content/30-content.qmd
            # - text: "31: Introduction to Interactive Maps"
            #   file: content/31-content.qmd  
            # - text: "32: Conclusion"
            #   file: content/32-content.qmd  
    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Self Assessments"
          contents:
            - text: "Self-reflection 1" 
              file: assignment/self-eval1.qmd
            - text: "Assignment Revision 1"
              file: assignment/05-firstrevision.qmd
            # - text: "Assignment Revision 2" 
            #   file: assignment/10-secondrevision.qmd
            # - text: "Assignment Revision 3" 
            #   file: assignment/13-thirdrevision.qmd
        - section: "Homework"
          contents:
            - text: "Introducing the course" 
              file: assignment/01-intro.qmd
            - text: "Spatial Data and Quarto"
              file: assignment/02-introspatial.qmd
            - text: "Vector Data"
              file: assignment/03-vector.qmd
            - text: "Predicates and Measures"
              file: assignment/04-maps.qmd
            - text: "Vector Operations"
              file: assignment/06-vectorops.qmd
            # - text: "Raster Operations" 
            #   file: assignment/07-rasterops.qmd
            # - text: "Spatial Databases" 
            #   file: assignment/08-combinations.qmd
            # - text: "Point Patterns and Interpolation" 
            #   file: assignment/09-pointpatterns.qmd
            # - text: "Statistical Modelling" 
            #   file: assignment/11-statmod.qmd
            # - text: "Movement and Networks" 
            #   file: assignment/12-nets.qmd
        - section: "Final Project"
          contents:
            - assignment/final-proj.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Getting started"
          contents:
            - text: "Introducing yourself to spatial data"
              file: example/session-4-example.qmd
            - text: "Quarto formatting"
              file: example/session-5-example.qmd
        - section: "Spatial operations in R"
          contents:
            - text: "CRS and Geometries"
              file: example/session-06-example.qmd
            - text: "Predicates and Measures"
              file: example/session-07-example.qmd
            - text: "Raster Predicates and Measures"
              file: example/session-08-example.qmd
            - text: "Intro to Mapping"
              file: example/session-09-example.qmd
            - text: "Vector Operations I"
              file: example/session-10-example.qmd
            - text: "Vector Operations II"
              file: example/session-11-example.qmd
            - text: "Raster Operations I"
              file: example/session-12-example.qmd
        #     - text: "Raster data"
        #       file: example/raster-intro.qmd
        #     - text: "Integrating vector and raster data"
        #       file: example/combining-data.qmd
        - section: "Statistical Workflows"
        #   contents:
        #     - text: "Building dataframes"
        #       file: example/intro-analysis.qmd
        #     - text: "Analyzing patterns"
        #       file: example/pattern-analysis.qmd
        #     - text: "Spatial Models"
        #       file: example/stat-analysis.qmd
        - section: "Visualizing Spatial Data"

    - title: "Lessons"
      contents:
        - section: "Overview"
          contents:
            - lesson/index.qmd
        - section: "Getting started"
          contents:
            - text: "Setup"
              file: lesson/getting-setup.qmd
            - text: "Data Classes"
              file: lesson/dataclasses.qmd
            - text: "Quarto"
              file: lesson/quarto.qmd
        - section: "Spatial operations in R"
          contents:
            - text: "Vector data"
              file: lesson/vector_intro.qmd
        #     - text: "Raster data"
        #       file: example/raster-intro.qmd
        #     - text: "Integrating vector and raster data"
        #       file: example/combining-data.qmd
        # - section: "Statistical workflows"
        #   contents:
        #     - text: "Building dataframes"
        #       file: example/intro-analysis.qmd
        #     - text: "Analyzing patterns"
        #       file: example/pattern-analysis.qmd
        #     - text: "Spatial Models"
        #       file: example/stat-analysis.qmd

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/lastyear.qmd
            - resource/data.qmd
        - section: "Guides"
          contents:
            - resource/install.qmd
            - resource/r.qmd
            - resource/rmarkdown.qmd
            - resource/git.qmd
            

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2024 by [Carolyn Koehn](https://scholar.google.com/citations?user=nscXWkcAAAAJ) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/CarolynKoehn/isdrfall2024.git)<br>
      Based on websites designed by [Andrew Heiss](https://github.com/andrewheiss/evalf22.classes.andrewheiss.com) and [Matt Williamson](https://github.com/mattwilliamson13/isdrfall2023)
format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: github
    